(function(global, factory) { function extractNS(){ var g = {}; return factory.call(g, global),g.jsnx;} if(typeof define === 'function' && define.amd){ /*AMD*/ define(extractNS); } else if (typeof module !== 'undefined' && module.exports){ /*node*/ module.exports = extractNS(); } else { factory.call(global, global); } }(this, function(window) {function h(a){throw a;}var aa=void 0,k=!0,l=null,n=!1;function ba(a){return function(){return a}}var p,ca=this;function da(){}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==aa}function ea(a){return"array"==q(a)}function t(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){return"string"==typeof a}function fa(a){return"boolean"==typeof a}function ga(a){return"function"==q(a)}function ha(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}var ia="closure_uid_"+(1E9*Math.random()>>>0),ja=0;
function ka(a,b,c){return a.call.apply(a.bind,arguments)}function la(a,b,c){a||h(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ma(a,b,c){ma=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return ma.apply(l,arguments)}
function x(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&s(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function na(a,b){function c(){}c.prototype=b.prototype;a.lb=b.prototype;a.prototype=new c;a.prototype.constructor=a};function oa(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a};var z=Array.prototype,ra=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(w(a))return!w(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},A=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=w(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=w(a)?a.split(""):
a,m=0;m<d;m++)if(m in g){var r=g[m];b.call(c,r,m,a)&&(e[f++]=r)}return e},ta=z.map?function(a,b,c){return z.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=w(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function ua(a,b){if(a.reduce)return a.reduce(b,0);var c=0;A(a,function(d,e){c=b.call(aa,c,d,e,a)});return c}
var va=z.some?function(a,b,c){return z.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=w(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return k;return n};function wa(a){if(!ea(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function xa(a,b){var c=ra(a,b);0<=c&&z.splice.call(a,c,1)}function ya(a){return z.concat.apply(z,arguments)}function Ca(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Da(a,b,c,d){z.splice.apply(a,Ea(arguments,1))}function Ea(a,b,c){return 2>=arguments.length?z.slice.call(a,b):z.slice.call(a,b,c)}function Fa(a,b,c){if(!t(a)||!t(b)||a.length!=b.length)return n;var d=a.length;c=c||Ga;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return n;return k}function La(a,b){return a>b?1:a<b?-1:0}function Ga(a,b){return a===b}
function Ma(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}}function Na(a){for(var b=Math.random,c=a.length-1;0<c;c--){var d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};var B="StopIteration"in ca?ca.StopIteration:Error("StopIteration");function C(){}C.prototype.next=function(){h(B)};C.prototype.v=function(){return this};function D(a){if(a instanceof C)return a;if("function"==typeof a.v)return a.v(n);if(t(a)){var b=0,c=new C;c.next=function(){for(;;){b>=a.length&&h(B);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}function E(a,b,c){if(t(a))try{A(a,b,c)}catch(d){d!==B&&h(d)}else{a=D(a);try{for(;;)b.call(c,a.next(),aa,a)}catch(e){e!==B&&h(e)}}}
function F(a,b,c){var d=D(a);a=new C;a.next=function(){for(;;){var a=d.next();return b.call(c,a,aa,d)}};return a}function Oa(a,b){var c=0;E(a,function(a){c=b.call(aa,c,a)});return c}function Pa(a){var b=arguments,c=b.length,d=0,e=new C;e.next=function(){try{return d>=c&&h(B),D(b[d]).next()}catch(a){return(a!==B||d>=c)&&h(a),d++,this.next()}};return e}function Qa(a){if(t(a))return Ca(a);a=D(a);var b=[];E(a,function(a){b.push(a)});return b}
function Ra(a,b){try{return D(a).next()}catch(c){return c!=B&&h(c),b}};function G(a,b){for(var c in a)b.call(aa,a[c],c,a)}function Ta(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function Ua(a){var b=0,c;for(c in a)b++;return b}function Va(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Wa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Xa(a){for(var b in a)delete a[b]}function Ya(a){"__d3datum__"in a&&delete a.__d3datum__}function H(a,b,c){return b in a?a[b]:c}function Za(a){var b={},c;for(c in a)b[c]=a[c];return b}var $a="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function J(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<$a.length;f++)c=$a[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var K={gb:function(a){return Math.floor(Math.random()*a)},mb:function(a,b){return a+Math.random()*(b-a)},$a:function(a,b,c){return Math.min(Math.max(a,b),c)},La:function(a,b){var c=a%b;return 0>c*b?c+b:c},cb:function(a,b,c){return a+c*(b-a)},fb:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},ja:function(a){return K.La(a,360)},wa:function(a){return a*Math.PI/180},Wa:function(a){return 180*a/Math.PI},Ya:function(a,b){return b*Math.cos(K.wa(a))},Za:function(a,b){return b*Math.sin(K.wa(a))},ma:function(a,
b,c,d){return K.ja(K.Wa(Math.atan2(d-b,c-a)))},Xa:function(a,b){var c=K.ja(b)-K.ja(a);180<c?c-=360:-180>=c&&(c=360+c);return c},jb:function(a){return 0==a?0:0>a?-1:1},eb:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],m=0;m<e+1;m++)g[m]=[],g[m][0]=0;for(var r=0;r<f+1;r++)g[0][r]=0;for(m=1;m<=e;m++)for(r=1;r<=e;r++)c(a[m-1],b[r-1])?g[m][r]=g[m-1][r-1]+1:g[m][r]=Math.max(g[m-1][r],g[m][r-1]);for(var u=[],m=e,r=f;0<m&&0<r;)c(a[m-1],b[r-
1])?(u.unshift(d(m-1,r-1)),m--,r--):g[m-1][r]>g[m][r-1]?m--:r--;return u},B:function(a){return ua(arguments,function(a,c){return a+c})},Da:function(a){return K.B.apply(l,arguments)/arguments.length},kb:function(a){var b=arguments.length;if(2>b)return 0;var c=K.Da.apply(l,arguments),b=K.B.apply(l,ta(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},bb:function(a){return isFinite(a)&&0==a%1},ab:function(a){return isFinite(a)&&!isNaN(a)},ib:function(a,b){return Math.floor(a+
(b||2E-15))},hb:function(a,b){return Math.ceil(a-(b||2E-15))}};function ab(a){var b=arguments;1===arguments.length&&t(arguments[0])&&(b=arguments[0]);this.Q="t";for(var c=0,d=b.length;c<d;c++)this[c]=b[c],this.Q+=bb(b[c]);this.length=b.length;b=this;Object.isFrozen&&!Object.isFrozen(this)&&(b=Object.create(this),Object.freeze(b));return b}ab.prototype.Q="";ab.prototype.length=0;x("jsnx.contrib.Tuple.prototype.length",ab.prototype.length);ab.prototype.toString=function(){return this.Q};x("jsnx.contrib.Tuple.prototype.toString",ab.prototype.toString);
function cb(a){return t(arguments[0])?new ab(arguments[0]):new ab(arguments)}x("jsnx.Tuple",cb);x("jsnx.t",cb);function db(a){this.name="JSNetworkXException";this.message=a}x("jsnx.exception.JSNetworkXException",db);db.prototype=Error();db.prototype.constructor=db;x("jsnx.JSNetworkXException",db);function L(a){db.call(this,a);this.name="JSNetworkXError"}na(L,db);x("jsnx.exception.JSNetworkXError",L);x("jsnx.JSNetworkXError",L);function eb(a){db.call(this,a);this.name="JSNetworkXPointlessConcept"}na(eb,db);x("jsnx.exception.JSNetworkXPointlessConcept",eb);x("jsnx.JSNetworkXPointlessConcept",eb);
function fb(a){db.call(this,a);this.name="JSNetworkXAlgorithmError"}na(fb,db);x("jsnx.exception.JSNetworkXAlgorithmError",fb);x("jsnx.JSNetworkXAlgorithmError",fb);function jb(a){fb.call(this,a);this.name="JSNetworkXUnfeasible"}na(jb,fb);x("jsnx.exception.JSNetworkXUnfeasible",jb);x("jsnx.JSNetworkXUnfeasible",jb);function kb(a){jb.call(this,a);this.name="JSNetworkXNoPath"}na(kb,jb);x("jsnx.exception.JSNetworkXNoPath",kb);x("jsnx.JSNetworkXNoPath",kb);
function lb(a){fb.call(this,a);this.name="JSNetworkXUnbounded"}na(lb,fb);x("jsnx.exception.JSNetworkXUnbounded",lb);x("jsnx.JSNetworkXUnbounded",lb);function N(a){this.name="KeyError";this.message=a}N.prototype=Error();N.prototype.constructor=N;x("jsnx.KeyError",N);x("jsnx.version","0.2.0");function bb(a,b){var c=typeof a;return"object"===c||"function"===c?a.hasOwnProperty("__hash__")?a.__hash__:a.toString!==Object.prototype.toString&&a.toString!==Array.prototype.toString?a.toString():b?b(a):"o"+(a[ia]||(a[ia]=++ja)):c.substr(0,1)+a}x("jsnx.contrib.misc.get_hash",bb);function O(a){this.u={};this.t={};this.s={};this.e={};if(a!=l)if(mb(a)||t(a))P(a,function(a){this.set.apply(this,a)},this);else if(ha(a))for(var b in a)this.set(isNaN(+b)?b:+b,a[b])}x("jsnx.contrib.Map",O);x("jsnx.Map",O);function nb(a,b){switch(typeof b){case "number":return a.t;case "string":return a.u;default:return a.s}}O.prototype.get=function(a,b){var c=nb(this,a);if("undefined"!==typeof c[a])return c[a];if(s(b))return b;h(new N("Map does not contain key "+ob(a)))};O.prototype.get=O.prototype.get;
O.prototype.a=function(a){return"undefined"!==typeof nb(this,a)[a]};O.prototype.has=O.prototype.a;O.prototype.set=function(a,b){var c=nb(this,a);c[a]=b;c===this.s&&(this.e[a]=a);return b};O.prototype.set=O.prototype.set;O.prototype.remove=function(a){var b=nb(this,a);"undefined"!==typeof b[a]?(delete b[a],b===this.s&&delete this.e[a]):h(new N("Map does not contain key "+ob(a)))};O.prototype.remove=O.prototype.remove;
O.prototype.L=function(){var a=[],b;for(b in this.t)a.push([+b,this.t[b]]);for(b in this.u)a.push([b,this.u[b]]);for(b in this.s)a.push([this.e[b],this.s[b]]);return a};O.prototype.items=O.prototype.L;O.prototype.copy=function(a){return pb(this,a)};O.prototype.keys=function(){return ta(Wa(this.t),function(a){return+a}).concat(Wa(this.u)).concat(Va(this.e))};O.prototype.keys=O.prototype.keys;O.prototype.n=function(){return Va(this.t).concat(Va(this.u)).concat(Va(this.s))};O.prototype.values=O.prototype.n;
O.prototype.v=function(){var a=new C,b=Wa(this.u),c=Wa(this.t),d=Wa(this.s),e=0,f=0,g=0;a.next=ma(function(){var a;if(e<c.length)return a=c[e++],[+a,this.t[a]];if(f<b.length)return a=b[f++],[a,this.u[a]];if(g<d.length)return a=d[g++],[this.e[a],this.s[a]];h(B)},this);return a};O.prototype.count=function(){return Ua(this.s)+Ua(this.t)+Ua(this.u)};O.prototype.count=O.prototype.count;O.prototype.clear=function(){Xa(this.u);Xa(this.t);Xa(this.s);Xa(this.e)};O.prototype.clear=O.prototype.clear;
O.prototype.forEach=function(a,b){E(this,function(c){a.apply(b,c)})};O.prototype.forEach=O.prototype.forEach;function Q(a){this.c=new O;a!=l&&(mb(a)||t(a))&&P(a,function(a){this.add(a)},this)}x("jsnx.contrib.Set",Q);x("jsnx.Set",Q);Q.prototype.a=function(a){return this.c.a(a)};Q.prototype.has=Q.prototype.a;Q.prototype.add=function(a){this.c.set(a,k)};Q.prototype.add=Q.prototype.add;Q.prototype.remove=function(a){try{this.c.remove(a)}catch(b){b instanceof N||h(b)}};Q.prototype.remove=Q.prototype.remove;Q.prototype.copy=function(a){return pb(this,a)};Q.prototype.n=function(){return this.c.keys()};
Q.prototype.values=Q.prototype.n;Q.prototype.v=function(){return F(this.c,function(a){return a[0]})};Q.prototype.C=function(a){for(var b=new Q(this.n()),c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof Q&&(e=e.n());for(var f=0,g=e.length;f<g;f++)b.remove(e[f])}return b};Q.prototype.difference=Q.prototype.C;Q.prototype.o=function(a){for(var b=new Q,c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof Q&&(e=e.n());for(var f=0,g=e.length;f<g;f++)this.a(e[f])&&b.add(e[f])}return b};
Q.prototype.intersection=Q.prototype.o;Q.prototype.count=function(){return this.c.count()};Q.prototype.count=Q.prototype.count;Q.prototype.clear=function(){this.c.clear()};Q.prototype.clear=Q.prototype.clear;Q.prototype.forEach=function(a,b){E(this,a,b)};Q.prototype.forEach=Q.prototype.forEach;x("jsnx.filter",function(a,b,c){var d=D(a);a=new C;a.next=function(){for(;;){var a=d.next();if(b.call(c,a,aa,d))return a}};return a});function qb(a){var b=0;s(b)||(b=l);var c=new O;P(a,function(a){c.set(a,b)});return c}function mb(a){return a!=l&&(a instanceof C||ga(a.v))}function rb(a){if(a instanceof R)return a.sa();if(w(a)||t(a))return a.length;if(sb(a))return Ua(a);h(new TypeError)}
function P(a,b,c,d){fa(c)&&(d=c,c=l);if(d){var e=b;b=function(a){e.apply(this,a)}}a instanceof R?E(tb(a),b,c):mb(a)?E(a,b,c):t(a)||w(a)?A(a,b,c):ha(a)&&P(Wa(a),b,c)}x("jsnx.forEach",P);function S(a,b,c){if(a instanceof R)return S(tb(a),b,c);if(t(a))return ta(a,b,c);if(mb(a))return F(a,b,c);if(ha(a))return Ta(a,b,c);h(new TypeError)}x("jsnx.map",S);
function ub(a){var b=arguments,c=b[0];if(t(c))return Ma.apply(l,b);if(mb(c)){var c=new C,d=b.length;c.next=function(){for(var a=[],c=0;c<d;c++)a.push(b[c].next());return a};return c}if(ha(c))return Ma.apply(l,ta(b,Wa));h(new TypeError)}function vb(a,b){a=ga(b)?T(S(a,function(){return b.apply(l,arguments)})):T(a);return Math.max.apply(l,a)}
function U(a,b,c){if(0===arguments.length)return D([]);1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new C,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(B);g=f;f+=c;return g};return d}
function wb(a){var b=T(a),c=b.length;if(2>c)return new C;var d=T(U(2));a=new C;a.next=function(){var a=ta(d,function(a){return b[a]});this.next=function(){var a=n,e;for(e=2;e--;)if(d[e]!=e+c-2){a=k;break}a||h(B);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return ta(d,function(a){return b[a]})};return a};return a}
function xb(a){var b=T(a),c=b.length;if(2>c)return new C;var d=T(U(c)),e=T(U(c,c-2,-1));a=new C;var f=new C,g,m=k;a.next=function(){this.next=g.next;return ta(d.slice(0,2),function(a){return b[a]})};f.next=function(){return m};g=X(f,function(a){a||h(B);m=n;return U(1,-1,-1)},function(a){if(!m)if(e[a]-=1,0===e[a])d.splice.apply(d,[a,d.length].concat(d.slice(a+1).concat([d[a]]))),e[a]=c-a;else{var f=e[a],g=d[a];d[a]=d[d.length-f];d[d.length-f]=g;m=k;return tb([ta(d.slice(0,2),function(a){return b[a]})])}},
function(a){return a});return a}function yb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!s(a[c])||"object"!==q(a[c])?a[c]=Y(d[c]):"object"===q(a[c])&&"object"===q(d)&&yb(a[c],d[c]);for(var f=0;f<$a.length;f++)c=$a[f],Object.prototype.hasOwnProperty.call(d,c)&&(!s(a[c])||"object"!==q(a[c])?a[c]=Y(d[c]):"object"===q(a[c])&&"object"===q(d)&&yb(a[c],d[c]))}}
function T(a){if(a instanceof R)return T(tb(a));if(t(a))return Ca(a);if(mb(a))return Qa(a);if(ha(a))return Wa(a);h(new TypeError)}x("jsnx.toArray",T);function zb(a){var b=new C,c=D(Wa(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function tb(a){if(a instanceof R)return tb(a.adj.keys());"object"===q(a)&&(!t(a)&&!mb(a))&&(a=Wa(a));return D(a)}
function X(a,b){var c=new C,d=Ea(arguments,1);if(0===d.length)return a;try{a=D(a)}catch(e){return c.next=function(){"Not implemented"===e.message&&h(new TypeError)},c}var f=0,g=d.length,m=[a];c.next=function(){do try{var a,b;do a=m[f].next(),s(a)&&(b=d[f](a));while(!s(a));if(mb(b)){if(f===g-1)return b;m.push(b);f+=1}else if(s(b))return b}catch(c){c!==B&&h(c),0<f?(m.pop(),f-=1):h(c)}while(1)};return c}x("jsnx.sentinelIterator",function(a,b){var c=new C;c.next=function(){return Ra(a,b)};return c});
function sb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==q(a)||a.nodeType||a==a.window)return n;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return n}catch(c){return n}for(var d in a);return d===aa||b.call(a,d)}
function Y(a,b){b=b||[];var c=q(a);if("object"==c&&(ga(a.copy)||sb(a))||"array"==c){for(var d=0,e=b.length;d<e;d+=2)if(a===b[d])return b[d+1];if(ga(a.copy))return c=a.copy(b),b.push(a,c),c;c="array"==c?[]:{};b.push(a,c);for(var f in a)c[f]=Y(a[f],b);return c}return a}function pb(a,b){function c(){}var d={},e,f;c.prototype=a.constructor.prototype;for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);d=Y(d,b);f=new c;for(e in d)f[e]=d[e];return f}var Bb=function Ab(b,c){return 0===c?b:Ab(c,b%c)};var Cb,Db=l,Eb="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
x("jsnx.draw",function(a,b,c){function d(){pa.g.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",$,")"].join("")});gc()}fa(b)&&(c=b,b=l);b=b||Db||{};var e=b.d3||window.d3,f={};yb(f,Fb,b);Db=b;e||h(Error("D3 requried for draw()"));f.element==l&&Cb==l&&h(Error("Output element required for draw()"));Cb=H(f,"element",Cb);e.select(Cb).select("svg.jsnx").remove();var g=e.select(Cb),m=g.append("svg").classed("jsnx",k).attr("pointer-events","all"),r=m.append("g");b=r.append("g").classed("edges",
k).selectAll("g.edge");var u=r.append("g").classed("nodes",k).selectAll("g.node"),v=e.layout.force(),y=f.width||parseInt(g.style("width"),10),I=f.height||parseInt(g.style("height"),10),Ha=f.layout_attr,g=f.nodelist||l,V,W,M,za=a.d(),qa=f.weighted,pa={g:u,h:b};if(f.with_labels){var Aa=f.labels;V="object"===q(Aa)?function(a){return H(Aa,a.node,"")}:ga(Aa)?Aa:w(Aa)?function(a){return a.data[Aa]}:function(a){return a.node}}f.labels=V;if(qa){var Ia=f.weights;M="object"===q(Ia)?function(a){return H(Ia,
a.node,1)}:ga(Ia)?Ia:w(Ia)?function(a){return H(a.data,Ia,1)}:ba(1)}if(f.with_edge_labels){var Ja=f.edge_labels;W=qa&&!s(Ja)?M:"object"===q(Ja)?function(a){return H(Aa,a.node,"")}:ga(Ja)?Ja:w(Ja)?function(a){return a.data[Ja]}:function(a){return a.edge};f.edge_labels=W}if(qa&&f.weighted_stroke){var qa=Oa(a.m(l,k),function(a,b){b=M({data:b[2]});return a>b?a:b}),sd=e.scale.linear().range([2,f.edge_style["stroke-width"]]).domain([0,qa]);f.edge_style["stroke-width"]=function(a){return sd(M.call(this,
a))}}m.select("svg.jsnx").remove();m.attr("width",y+"px").attr("height",I+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var td={size:k,nodes:k,links:k,start:k};P(Ha,function(a){if(!(a in td))v[a](Ha[a])});v.nodes([]).links([]).size([y,I]);var Sa=1,$=1;if(f.pan_zoom.enabled){var hc=f.pan_zoom.scale;(function(){var a=n,b=1,c=Sa;m.call(e.behavior.zoom().on("zoom",function(){var f=e.event.sourceEvent.shiftKey;(f=hc&&f||!(hc||f))&&!a?(b=e.event.scale,c=Sa,a=k):!f&&a&&(a=n);
Sa=f?c*(e.event.scale/b):Sa;$=!f?Sa/e.event.scale:$;f=e.event.translate;r.attr("transform","translate("+f[0]+","+f[1]+")scale("+e.event.scale+")");d()}))})()}var gc=da,Ba=f.edge_offset,gb=f.node_attr.r,hb=f.node_style["stroke-width"];"circle"===f.node_shape?(ga(gb)||(gb=function(){return f.node_attr.r}),ga(hb)||(hb=function(){return f.node_style["stroke-width"]}),Ba=function(a){return[gb(a.source)+hb(a.source),gb(a.target)+hb(a.target)]}):(ea(Ba)&&(Ba=function(){return f.edge_offset}),"number"==typeof Ba&&
(Ba=function(){return[f.edge_offset,f.edge_offset]}));var Ka=f.edge_style["stroke-width"];ga(Ka)||(Ka=function(){return f.edge_style["stroke-width"]});var ib=f.edge_label_offset,gc=za?function(){pa.h.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,m=K.ma(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Ba(a),g=[g[0]*$,g[1]*$];b.attr("transform",["translate(",c,",",d,")rotate(",m,")"].join(""));c=Ka(a)*$;d=f-g[1]-2*c;m=c/2;b.select(".line").attr("d",
["M",g[0],0,"L",g[0],-m,"L",d,-m,"L",d,-c,"L",f-g[1],0,"z"].join(" "));c=1/$;b.select("text").attr("x",ib.x*c+g[0]+(f*c-g[0]-g[1])/2).attr("y",-Ka(a)/2+-ib.y*c).attr("transform","scale("+$+")")}})}:function(){pa.h.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,m=a.target.y,r=K.ma(c,d,g,m),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(m-d,2)),m=g/2,u=Ba(a),u=[u[0]*$,u[1]*$],v=1/$,y=Ka(a)*$,I=90<r&&279>r;b.attr("transform",["translate(",c,",",d,")rotate(",
r,")"].join(""));b.select(".line").attr("d",["M",u[0],y/4,"L",u[0],-y/4,"L",g-u[1],-y/4,"L",g-u[1],y/4,"z"].join(" "));f.with_edge_labels&&b.select("text").attr("x",(I?1:-1)*ib.x*v+u[0]+(g*v-u[0]-u[1])/2).attr("y",-Ka(a)/4+-ib.y*v).attr("transform","scale("+$+")"+(I?"rotate(180,"+m*(1/$)+",0)":""))}})};v.on("tick",d);y=a.H();I=a.m();g&&(c=n,y=a.j(g),I=a.m(g));pa.g=Gb(a,y,v,u,f.node_shape,V);pa.h=Hb(a,I,v,b,W);Ib(pa.g,{attr:f.node_attr,style:f.node_style,N:f.label_style,M:f.label_attr},f.with_labels);
Jb(pa.h,{attr:f.edge_attr,style:f.edge_style,N:f.edge_label_style,M:f.edge_label_attr},f.with_edge_labels,l,za);c?Kb(a,v,f,pa):a.bound?Lb(a):Mb(a);v.start();return v});function Gb(a,b,c,d,e,f){var g=c.nodes();P(b,function(b){var c=a.node.get(b);b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Nb);b=d.enter().append("g").classed("node",k).call(c.drag);b.append(e).classed("node-shape",k);f&&b.append("text").text(f);return d}
function Hb(a,b,c,d,e){var f=c.links();P(b,function(b){var c=b[0],d=b[1];b=b[2]||a.ea(c,d);c={edge:[c,d],redge:[d,c],source:a.node.get(c).__d3datum__,target:a.node.get(d).__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,Ob);b=d.enter().append("g").classed("edge",k);b.append("path").classed("line",k);e&&b.append("text").text(e);return d}
function Ib(a,b,c,d){if(d!=l){var e={};P(d,function(a){e[t(a)?a[0]:a]=k});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");G(b.attr,function(a,b){f.attr(b,a)});G(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");G(b.M,function(a,b){g.attr(b,a)});G(b.N,function(a,b){g.style(b,a)})}}
function Jb(a,b,c,d,e){if(d!=l){var f={};P(d,function(a){f[[a[0],a[1]]]=k});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");G(b.attr,function(a,b){g.attr(b,a)});G(b.style,function(a,b){"stroke-width"!=b&&g.style(b,a)});g.style("stroke-width",0);if(c){var m=a.selectAll("text");G(b.M,function(a,b){m.attr(b,a)});G(b.N,function(a,b){m.style(b,a)})}}function Nb(a){return a.node}function Ob(a){return a.edge}
function Pb(a,b,c,d){var e=c.nodes();P(a.j(b),function(b){xa(e,a.node.get(b).__d3datum__)});d=d.data(e,Nb);d.exit().remove();return d}function Qb(a,b,c,d){var e=c.links();P(b,function(b){xa(e,H(a.ea(b[0],b[1],{}),"__d3datum__",l))});d=d.data(e,Ob);d.exit().remove();return d}
function Kb(a,b,c,d){Lb(a,n);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,M:c.label_attr,N:c.label_style},m={attr:c.edge_attr,style:c.edge_style,M:c.edge_label_attr,N:c.edge_label_style},r=c.labels,u=c.edge_labels,v=c.with_labels,y=c.with_edge_labels,I=a.d();a.add_node=a.I=function(a){var c=!this.l(a);e.add_node.apply(this,arguments);c&&(d.g=Gb(this,[a],b,d.g,f,r));Ib(d.g,g,v,[a]);b.start()};a.add_nodes_from=a.i=function(a){var c=sa(T(a),function(a){return!this.l(t(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.g=Gb(this,c,b,d.g,f,r));Ib(d.g,g,v,a);b.start()};a.add_edge=a.b=function(c,V){var W=!this.fa(c,V),M=[];W&&(M=sa(c==V?[c]:[c,V],function(a){return!this.l(a)},this));e.add_edge.apply(a,arguments);0<M.length&&(d.g=Gb(this,M,b,d.g,f,r),Ib(d.g,g,v,M));W&&(d.h=Hb(this,[[c,V]],b,d.h,u));Jb(d.h,m,y,[[c,V]],I);b.start()};a.add_edges_from=a.f=function(c){var I=[],W=[],M={},za={},qa=this.d();P(c,function(a){var b=a[0];a=a[1];if(!this.fa(b,
a)&&!([b,a]in M)&&(qa||!([a,b]in M)))I.push([b,a]),M[[b,a]]=k,!this.l(b)&&!(b in za)&&(W.push(b),za[b]=k),!this.l(a)&&!(a in za)&&(W.push(a),za[a]=k)},this);e.add_edges_from.apply(a,arguments);0<W.length&&(d.g=Gb(this,W,b,d.g,f,r),Ib(d.g,g,v,W));0<I.length&&(d.h=Hb(this,I,b,d.h,u));Jb(d.h,m,y,I,qa);b.start()};a.remove_node=a.X=function(c){try{if(this.l(c)){d.g=Pb(this,[c],b,d.g);var f=this.m([c]);this.d()&&(f=Pa(f,this.T([c])));d.h=Qb(this,f,b,d.h);b.resume()}}catch(g){}e.remove_node.apply(a,arguments)};
a.remove_nodes_from=a.Y=function(c){try{d.g=Pb(this,c,b,d.g);var f=this.m(c);this.d()&&(f=Pa(f,this.T(c)));d.h=Qb(this,f,b,d.h);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.V=function(c,f){try{d.h=Qb(this,[[c,f]],b,d.h),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.W=function(c){try{d.h=Qb(this,c,b,d.h),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.g=d.g.data([],Nb);d.g.exit().remove();d.h=d.h.data([],
Ob);d.h.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=k}x("jsnx.is_bound",function(a){return a.bound});function Lb(a,b){if(a.bound){var c=a.constructor.prototype;A(Eb,function(b){a[b]=c[b]});delete a.bound;(!s(b)||b)&&Mb(a)}}x("jsnx.unbind",Lb);function Mb(a){P(a.H(k),function(a){Ya(a[1])});P(a.m(l,k),function(a){Ya(a[2])})}
var Fb={layout_attr:{charge:-120,linkDistance:60},node_shape:"circle",node_attr:{r:10},node_style:{"stroke-width":2,stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{fill:"#000","stroke-width":3},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","text-anchor":"middle","-webkit-user-select":"none"},edge_label_offset:{x:0,y:0.5},with_labels:n,
with_edge_labels:n,edge_offset:10,weighted:n,weights:"weight",weighted_stroke:k,pan_zoom:{enabled:k,scale:k}};function Rb(a,b){var c=new O;if(b!=l){b=T(b);var d=function(a){return 0<=ra(b,a)};A(b,function(b){c.set(b,sa(a.F(b),d))})}else P(a,function(b){c.set(b,a.F(b))});return c}x("jsnx.contrib.convert.to_map_of_lists",Rb);x("jsnx.to_map_of_lists",Rb);function Sb(a,b){var c=Tb(b);c.i(a.keys());a.forEach(function(a,b){A(b,function(b){c.b(a,b)})});return c}x("jsnx.contrib.convert.from_map_of_lists",Sb);
x("jsnx.contrib.convert.to_map_of_maps",function(a,b,c){var d=new O;b!=l?(b=T(b),c!=l?A(b,function(e){var f=d.set(e,new O);a.get(e).forEach(function(a){0<=ra(b,a)&&f.set(a,c)})}):A(b,function(c){var f=d.set(c,new O);a.get(c).forEach(function(a,c){0<=ra(b,a)&&f.set(a,c)})})):c!=l?E(a.q(),function(a,b){var g=d.set(b,new O);a.forEach(function(a){g.set(a,c)})}):E(a.q(),function(a,b){var c=d.set(b,new O);a.forEach(function(a,b){c.set(a,b)})});return d});
function Ub(a,b,c){var d=Tb(b),e=new O,f=[];d.i(a.keys());c?d.d()?a.forEach(function(a,b){t(b)&&h(Error());b.forEach(function(b,c){G(c,function(c){d.b(a,b,c)})})}):a.forEach(function(a,b){t(b)&&h(Error());b.forEach(function(b,c){f[0]=a;f[1]=b;e.a(f)||(G(c,function(c){d.b(a,b,c)}),f[0]=b,f[1]=a,e.set(f,1))})}):a.forEach(function(a,b){t(b)&&h(Error());b.forEach(function(b,c){d.b(a,b,c)})});return d}x("jsnx.contrib.convert.from_map_of_maps",Ub);function Vb(a){if("function"==typeof a.D)return a.D();if(w(a))return a.split("");if(t(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Va(a)};function Wb(a,b){this.c={};this.e=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.ca(a)}p=Wb.prototype;p.w=0;p.P=0;p.S=function(){return this.w};p.D=function(){Xb(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.c[this.e[b]]);return a};p.da=function(){Xb(this);return this.e.concat()};p.na=function(a){return Yb(this.c,a)};p.U=function(){return 0==this.w};
p.clear=function(){this.c={};this.P=this.w=this.e.length=0};p.remove=function(a){return Yb(this.c,a)?(delete this.c[a],this.w--,this.P++,this.e.length>2*this.w&&Xb(this),k):n};function Xb(a){if(a.w!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];Yb(a.c,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.w!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],Yb(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}p.get=function(a,b){return Yb(this.c,a)?this.c[a]:b};
p.set=function(a,b){Yb(this.c,a)||(this.w++,this.e.push(a),this.P++);this.c[a]=b};p.ca=function(a){var b;a instanceof Wb?(b=a.da(),a=a.D()):(b=Wa(a),a=Va(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.R=function(){return new Wb(this)};p.v=function(a){Xb(this);var b=0,c=this.e,d=this.c,e=this.P,f=this,g=new C;g.next=function(){for(;;){e!=f.P&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(B);var g=c[b++];return a?g:d[g]}};return g};
function Yb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Zb(a){this.c=new Wb;a&&this.ca(a)}function $b(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ia]||(a[ia]=++ja)):b.substr(0,1)+a}p=Zb.prototype;p.S=function(){return this.c.S()};p.add=function(a){this.c.set($b(a),a)};p.ca=function(a){a=Vb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.remove=function(a){return this.c.remove($b(a))};p.clear=function(){this.c.clear()};p.U=function(){return this.c.U()};p.contains=function(a){return this.c.na($b(a))};
p.o=function(a){var b=new Zb;a=Vb(a);for(var c=0;c<a.length;c++){var d=a[c];this.contains(d)&&b.add(d)}return b};p.C=function(a){var b=this.R();a=Vb(a);for(var c=a.length,d=0;d<c;d++)b.remove(a[d]);return b};p.D=function(){return this.c.D()};p.R=function(){return new Zb(this)};p.v=function(){return this.c.v(n)};function Tb(a){if(a!=l)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new R;return a}
function ac(a,b,c){var d=l;if(a.hasOwnProperty("adj"))try{return d=Ub(a.adj,b,n),"graph"in a&&"object"===q(a.graph)&&(d.graph=Za(a.graph)),"node"in a&&a.node instanceof O&&(d.node=new O,a.node.forEach(function(a,b){d.node.set(a,Za(b))})),d}catch(e){h(e)}if(a instanceof O)try{return Ub(a,b,c)}catch(f){try{return Sb(a,b)}catch(g){h(Error("Input is not known type."))}}if("object"===q(a))try{return bc(a,b,c)}catch(m){try{return cc(a,b)}catch(r){h(Error("Input is not known type."))}}if(t(a))try{return dc(a,
b)}catch(u){h(Error("Input is not valid edge list"))}return d}x("jsnx.convert.to_networkx_graph",ac);x("jsnx.to_networkx_graph",ac);function ec(a){return a.ba()}x("jsnx.convert.convert_to_undirected",ec);x("jsnx.convert_to_undirected",ec);function fc(a){return a.aa()}x("jsnx.convert.convert_to_directed",fc);x("jsnx.convert_to_undirected",fc);function ic(a,b){function c(a){return 0<=ra(b,a)}var d={};b!=l?b=T(b):(b=a,c=function(a){return b.l(a)});P(b,function(b){d[b]=sa(a.F(b),c)});return d}
x("jsnx.convert.to_dict_of_lists",ic);x("jsnx.to_dict_of_lists",ic);function cc(a,b){var c=Tb(b);c.i(F(zb(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));var d=[];G(a,function(a,b){b=isNaN(b)?b:+b;A(a,function(a){d.push([b,a])})});c.f(d);return c}x("jsnx.convert.from_dict_of_lists",cc);
x("jsnx.convert.to_dict_of_dicts",function(a,b,c){var d={};b!=l?(b=T(b),c!=l?A(b,function(e){d[e]={};G(a.get(e),function(a,g){0<=ra(b,g)&&(d[e][g]=c)})}):A(b,function(c){d[c]={};G(a.get(c),function(a,g){0<=ra(b,g)&&(d[c][g]=a)})})):c!=l?E(a.q(),function(a,b){d[b]=Ta(a,function(){return c})}):E(a.q(),function(a,b){d[b]=Za(a)});return d});
function bc(a,b,c){var d=Tb(b),e,f;d.i(F(zb(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));c?d.d()?(e=[],G(a,function(a,b){t(a)&&h(Error());b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;G(a,function(a){e.push([b,c,a])})})}),d.f(e)):(f=new Zb,G(a,function(a,b){t(a)&&h(Error());b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,c].toString())||(e=[],G(a,function(a){e.push([b,c,a])}),d.f(e),f.add([c,b].toString()))})})):(e=[],G(a,function(a,b){t(a)&&h(Error());b=isNaN(b)?b:+b;G(a,function(a,
c){c=isNaN(c)?c:+c;e.push([b,c,a])})}),d.f(e));return d}x("jsnx.convert.from_dict_of_dicts",bc);x("jsnx.convert.to_edgelist",function(a,b){return b!=l?a.K(b,k):a.K(l,k)});function dc(a,b){var c=Tb(b);c.f(a);return c}x("jsnx.convert.from_edgelist",dc);function ob(a){var b=[];jc(new kc,a,b);return b.join("")}function kc(){this.Z=aa}
function jc(a,b,c){switch(typeof b){case "string":lc(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(ea(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],jc(a,a.Z?a.Z.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),lc(f,c),c.push(":"),
jc(a,a.Z?a.Z.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var mc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},nc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function lc(a,b){b.push('"',a.replace(nc,function(a){if(a in mc)return mc[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return mc[a]=e+b.toString(16)}),'"')};function R(a,b){if(!(this instanceof R))return new R(a,b);this.graph={};this.node=new O;this.adj=new O;a!=l&&ac(a,this);J(this.graph,b||{});this.edge=this.adj}x("jsnx.classes.Graph",R);x("jsnx.Graph",R);R.__name__="Graph";R.prototype.Ga=l;R.prototype.graph=R.prototype.Ga;R.prototype.Na=l;R.prototype.node=R.prototype.Na;R.prototype.Ba=l;R.prototype.adj=R.prototype.Ba;R.prototype.Fa=l;R.prototype.edge=R.prototype.Fa;
R.prototype.name=function(a){if(s(a))this.graph.name=a.toString();else return this.graph.name||""};R.prototype.name=R.prototype.name;R.prototype.toString=function(){return this.name()};R.prototype.toString=R.prototype.toString;R.prototype.get=function(a){try{return this.adj.get(a)}catch(b){b instanceof N||h(b),h(new N("Graph does not contain node "+a+"."))}};R.prototype.get=R.prototype.get;
R.prototype.I=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new L("The attr_dict argument must be an object."));this.adj.a(a)?J(this.node.get(a),b):(this.adj.set(a,new O),this.node.set(a,b))};R.prototype.add_node=R.prototype.I;
R.prototype.i=function(a,b){b!=l||(b={});P(a,function(a){if(ea(a)&&2===a.length&&ha(a[1])){var d=a[0];a=a[1];if(this.adj.a(d))d=this.node.get(d),J(d,b,a);else{this.adj.set(d,new O);var e=Za(b);J(e,a);this.node.set(d,e)}}else this.adj.a(a)?J(this.node.get(a),b):(this.adj.set(a,new O),this.node.set(a,Za(b)))},this)};R.prototype.add_nodes_from=R.prototype.i;
R.prototype.X=function(a){var b=this.adj;try{var c=this.adj.get(a).keys();this.node.remove(a);A(c,function(c){b.get(c).remove(a)});b.remove(a)}catch(d){d instanceof N||h(d),h(new L(oa("The node %s is not in the graph",ob(a))))}};R.prototype.remove_node=R.prototype.X;R.prototype.Y=function(a){var b=this.adj;P(a,function(a){try{this.node.remove(a),b.get(a).forEach(function(d){b.get(d).remove(a)}),b.remove(a)}catch(d){d instanceof N||h(d)}},this)};R.prototype.remove_nodes_from=R.prototype.Y;
R.prototype.H=function(a){return a?D(this.node):D(this.adj.keys())};R.prototype.nodes_iter=R.prototype.H;R.prototype.nodes=function(a){return a?this.node.L():this.node.keys()};R.prototype.nodes=R.prototype.nodes;R.prototype.sa=function(){return this.adj.count()};R.prototype.number_of_nodes=R.prototype.sa;R.prototype.A=function(){return this.adj.count()};R.prototype.order=R.prototype.A;R.prototype.l=function(a){try{return this.adj.a(a)}catch(b){if(b instanceof TypeError)return n;h(b)}};
R.prototype.has_node=R.prototype.l;R.prototype.b=function(a,b,c){c=c||{};"object"!==q(c)&&h(new L("The attr_dict argument must be an object."));this.adj.a(a)||(this.adj.set(a,new O),this.node.set(a,{}));this.adj.a(b)||(this.adj.set(b,new O),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});J(d,c);this.adj.get(a).set(b,d);this.adj.get(b).set(a,d)};R.prototype.add_edge=R.prototype.b;
R.prototype.f=function(a,b){b=b||{};"object"!==q(b)&&h(new L("The attr_dict argument must be an object."));P(a,function(a){var d=rb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new L(oa("Edge tuple %s must be a 2-tuple or 3-tuple.",ob(a))));this.adj.a(e)||(this.adj.set(e,new O),this.node.set(e,{}));this.adj.a(f)||(this.adj.set(f,new O),this.node.set(f,{}));a=this.adj.get(e).get(f,{});J(a,b,g);this.adj.get(e).set(f,a);this.adj.get(f).set(e,a)},this)};
R.prototype.add_edges_from=R.prototype.f;R.prototype.Aa=function(a,b,c){c=c||{};w(b)||(c=b,b="weight");this.f(S(a,function(a){var c={};c[b]=a[2];s(c[b])||h(new TypeError("Values must consist of three elements: "+ob(a)));return[a[0],a[1],c]}),c)};R.prototype.add_weighted_edges_from=R.prototype.Aa;R.prototype.V=function(a,b){try{this.adj.get(a).remove(b),bb(a)!==bb(b)&&this.adj.get(b).remove(a)}catch(c){c instanceof N&&h(new L(oa("The edge %s-%s is not in the graph",ob(a),ob(b)))),h(c)}};
R.prototype.remove_edge=R.prototype.V;R.prototype.W=function(a){P(a,function(a){var c=a[0];a=a[1];this.adj.a(c)&&this.adj.get(c).a(a)&&(this.adj.get(c).remove(a),bb(c)!==bb(a)&&this.adj.get(a).remove(c))},this)};R.prototype.remove_edges_from=R.prototype.W;R.prototype.fa=function(a,b){return this.adj.a(a)&&this.adj.get(a).a(b)};R.prototype.has_edge=R.prototype.fa;
R.prototype.F=function(a){try{return this.adj.get(a).keys()}catch(b){b instanceof N&&h(new L(oa("The node %s is not in the graph.",ob(a)))),h(b)}};R.prototype.neighbors=R.prototype.F;R.prototype.O=function(a){try{return D(this.adj.get(a).keys())}catch(b){b instanceof N&&h(new L(oa("The node %s is not in the graph.",ob(a)))),h(b)}};R.prototype.neighbors_iter=R.prototype.O;R.prototype.K=function(a,b){return Qa(this.m(a,b))};R.prototype.edges=R.prototype.K;
R.prototype.m=function(a,b){fa(a)&&(b=a,a=l);var c=new O,d,e;d=a!=l?F(this.j(a),function(a){return[a,this.adj.get(a)]},this):D(this.adj);return b?X(d,function(a){e=a[0];var b=new C,d=D(a[1]);b.next=function(){try{return d.next()}catch(a){a===B&&c.set(e,1),h(a)}};return b},function(a){if(!c.a(a[0]))return[e,a[0],a[1]]}):X(d,function(a){e=a[0];var b=new C,d=D(a[1]);b.next=function(){try{return d.next()}catch(a){a===B&&c.set(e,1),h(a)}};return b},function(a){if(!c.a(a[0]))return[e,a[0]]})};
R.prototype.edges_iter=R.prototype.m;R.prototype.ea=function(a,b,c){try{return this.adj.get(a).get(b)}catch(d){if(d instanceof N)return c;h(d)}};R.prototype.get_edge_data=R.prototype.ea;R.prototype.Ca=function(){return Qa(F(this.q(),function(a){return a[1].keys()}))};R.prototype.adjacency_list=R.prototype.Ca;R.prototype.q=function(){return D(this.adj)};R.prototype.adjacency_iter=R.prototype.q;R.prototype.z=function(a,b){return a!=l&&this.l(a)?this.J(a,b).next()[1]:new O(this.J(a,b))};
R.prototype.degree=R.prototype.z;R.prototype.J=function(a,b){var c;c=a!=l?F(this.j(a),function(a){return[a,this.adj.get(a)]},this):D(this.adj);return b?F(c,function(a){var c=a[0],f=a[1],g=0;f.forEach(function(a,c){g+=+H(c,b,1)});g+=+(f.a(c)&&H(f.get(c),b,1));a[1]=g;return a}):F(c,function(a){a[1]=a[1].count()+ +a[1].a(a[0]);return a})};R.prototype.degree_iter=R.prototype.J;R.prototype.clear=function(){this.name("");this.adj.clear();this.node.clear();Xa(this.graph)};R.prototype.clear=R.prototype.clear;
R.prototype.copy=function(){return pb(this)};R.prototype.copy=R.prototype.copy;R.prototype.ha=ba(n);R.prototype.is_multigraph=R.prototype.ha;R.prototype.d=ba(n);R.prototype.is_directed=R.prototype.d;R.prototype.aa=function(){var a=new Z;a.name(this.name());a.i(this);a.f(function(){var a;return X(this.q(),function(c){a=c[0];return D(c[1])},function(c){c[2]=Y(c[1]);c[1]=c[0];c[0]=a;return c})}.call(this));a.graph=Y(this.graph);a.node=Y(this.node);return a};R.prototype.to_directed=R.prototype.aa;
R.prototype.ba=function(){return pb(this)};R.prototype.to_undirected=R.prototype.ba;R.prototype.$=function(a){a=this.j(a);var b=new this.constructor,c=b.adj,d=this.adj;E(a,function(a){var b=new O;c.set(a,b);d.get(a).forEach(function(d,m){c.a(d)&&(b.set(d,m),c.get(d).set(a,m))})});P(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};R.prototype.subgraph=R.prototype.$;R.prototype.Oa=function(){return ta(sa(this.adj.L(),function(a){return a[1].a(a[0])}),function(a){return a[0]})};
R.prototype.nodes_with_selfloops=R.prototype.Oa;R.prototype.ua=function(a){return a?ta(sa(this.adj.L(),function(a){return a[1].a(a[0])}),function(a){a[2]=a[1].get(a[0]);a[1]=a[0];return a}):ta(sa(this.adj.L(),function(a){return a[1].a(a[0])}),function(a){a[1]=a[0];return a})};R.prototype.selfloop_edges=R.prototype.ua;R.prototype.Pa=function(){return this.ua().length};R.prototype.number_of_selfloops=R.prototype.Pa;R.prototype.size=function(a){var b=K.B.apply(l,this.z(l,a).n())/2;return a!=l?b:Math.floor(b)};
R.prototype.size=R.prototype.size;R.prototype.ra=function(a,b){return a==l?Math.floor(this.size()):this.adj.get(a).a(b)?1:0};R.prototype.number_of_edges=R.prototype.ra;R.prototype.za=function(a,b){var c=T(a),d=c[0],c=F(Ea(c,1),function(a){return[d,a]});this.f(c,b)};R.prototype.add_star=R.prototype.za;R.prototype.ya=function(a,b){var c=T(a),c=Ma(Ea(c,0,c.length-1),Ea(c,1));this.f(c,b)};R.prototype.add_path=R.prototype.ya;R.prototype.xa=function(a,b){var c=T(a),c=Ma(c,ya(Ea(c,1),[c[0]]));this.f(c,b)};
R.prototype.add_cycle=R.prototype.xa;R.prototype.j=function(a){return a!=l?this.l(a)?D([a]):function(a,c){var d=new C,e=X(a,function(a){if(c.a(a))return a});d.next=function(){try{return e.next()}catch(a){a instanceof TypeError&&h(new L("nbunch is not a node or a sequence of nodes")),h(a)}};return d}(a,this.adj):D(this.adj.keys())};R.prototype.nbunch_iter=R.prototype.j;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);this.graph={};this.node=new O;this.adj=new O;this.pred=new O;this.succ=this.adj;a!=l&&ac(a,this);J(this.graph,b||{});this.edge=this.adj}x("jsnx.classes.DiGraph",Z);x("jsnx.DiGraph",Z);na(Z,R);Z.__name__="DiGraph";Z.prototype.Ta=l;Z.prototype.pred=Z.prototype.Ta;Z.prototype.Va=l;Z.prototype.succ=Z.prototype.Va;
Z.prototype.I=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new L("The attr_dict argument must be an object."));this.succ.a(a)?J(this.node.get(a),b):(this.succ.set(a,new O),this.pred.set(a,new O),this.node.set(a,b))};Z.prototype.add_node=Z.prototype.I;
Z.prototype.i=function(a,b){var c,d,e,f,g;b!=l||(b={});P(tb(a),function(a){c=!this.succ.a(a);ea(a)&&2===a.length&&ha(a[1])?(d=a[0],e=a[1],this.succ.a(d)?(g=this.node.get(d),J(g,b,e)):(this.succ.set(d,new O),this.pred.set(d,new O),f=Za(b),J(f,e),this.node.set(d,f))):c?(this.succ.set(a,new O),this.pred.set(a,new O),this.node.set(a,Za(b))):J(this.node.get(a),b)},this)};Z.prototype.add_nodes_from=Z.prototype.i;
Z.prototype.X=function(a){var b;try{b=this.succ.get(a),this.node.remove(a)}catch(c){c instanceof N||h(c),h(new L(oa("The node %s is not in the graph",ob(a))))}b.forEach(function(b){this.pred.get(b).remove(a)},this);this.succ.remove(a);this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this);this.pred.remove(a)};Z.prototype.remove_node=Z.prototype.X;
Z.prototype.Y=function(a){var b;P(a,function(a){this.succ.a(a)&&(b=this.succ.get(a),this.node.remove(a),b.forEach(function(b){this.pred.get(b).remove(a)},this),this.succ.remove(a),this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this),this.pred.remove(a))},this)};Z.prototype.remove_nodes_from=Z.prototype.Y;
Z.prototype.b=function(a,b,c){c=c||{};"object"!==q(c)&&h(new L("The attr_dict argument must be an object."));this.succ.a(a)||(this.succ.set(a,new O),this.pred.set(a,new O),this.node.set(a,{}));this.succ.a(b)||(this.succ.set(b,new O),this.pred.set(b,new O),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});J(d,c);this.succ.get(a).set(b,d);this.pred.get(b).set(a,d)};Z.prototype.add_edge=Z.prototype.b;
Z.prototype.f=function(a,b){b=b||{};"object"!==q(b)&&h(new L("The attr_dict argument must be an object."));P(a,function(a){var d=rb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new L("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));this.succ.a(e)||(this.succ.set(e,new O),this.pred.set(e,new O),this.node.set(e,{}));this.succ.a(f)||(this.succ.set(f,new O),this.pred.set(f,new O),this.node.set(f,{}));a=this.adj.get(e).get(f,{});J(a,b,g);this.succ.get(e).set(f,a);this.pred.get(f).set(e,
a)},this)};Z.prototype.add_edges_from=Z.prototype.f;Z.prototype.V=function(a,b){try{this.succ.get(a).remove(b),this.pred.get(b).remove(a)}catch(c){c instanceof TypeError&&h(new L(oa("The edge %s-%s is not in the graph",ob(a),ob(b)))),h(c)}};Z.prototype.remove_edge=Z.prototype.V;Z.prototype.W=function(a){P(a,function(a){var c=a[0];a=a[1];try{this.succ.get(c).remove(a),this.pred.get(a).remove(c)}catch(d){}},this)};Z.prototype.remove_edges_from=Z.prototype.W;
Z.prototype.Ia=function(a,b){return this.succ.a(a)&&this.succ.get(a).a(b)};Z.prototype.has_successor=Z.prototype.Ia;Z.prototype.Ha=function(a,b){return this.pred.a(a)&&this.pred.get(a).a(b)};Z.prototype.has_predecessor=Z.prototype.Ha;Z.prototype.ka=function(a){try{return F(this.succ.get(a),function(a){return a[0]})}catch(b){b instanceof N||h(b),h(new L("The node "+a+" is not in the digraph."))}};Z.prototype.successors_iter=Z.prototype.ka;
Z.prototype.ta=function(a){try{return F(this.pred.get(a),function(a){return a[0]})}catch(b){b instanceof N||h(b),h(new L("The node "+a+" is not in the digraph."))}};Z.prototype.predecessors_iter=Z.prototype.ta;Z.prototype.va=function(a){try{return this.succ.get(a).keys()}catch(b){b instanceof N||h(b),h(new L("The node "+a+" is not in the digraph."))}};Z.prototype.successors=Z.prototype.va;
Z.prototype.Ua=function(a){try{return this.pred.get(a).keys()}catch(b){b instanceof N||h(b),h(new L("The node "+a+" is not in the digraph."))}};Z.prototype.predecessors=Z.prototype.Ua;Z.prototype.F=Z.prototype.va;Z.prototype.neighbors=Z.prototype.F;Z.prototype.O=Z.prototype.ka;Z.prototype.neighbors_iter=Z.prototype.O;
Z.prototype.m=function(a,b){fa(a)&&(b=a,a=l);var c,d;if(a!=l){var e=[];c=S(this.j(a),function(a){e[0]=a;e[1]=this.adj.get(a);return e},this)}else c=this.adj;return b?X(c,function(a){d=a[0];return D(a[1])},function(a){return[d,a[0],a[1]]}):X(c,function(a){d=a[0];return D(a[1])},function(a){return[d,a[0]]})};Z.prototype.edges_iter=Z.prototype.m;Z.prototype.Sa=Z.prototype.m;Z.prototype.out_edges_iter=Z.prototype.Sa;Z.prototype.Ra=R.prototype.K;Z.prototype.out_edges=Z.prototype.Ra;
Z.prototype.T=function(a,b){fa(a)&&(b=a,a=l);var c,d;if(a!=l){var e=[];c=S(this.j(a),function(a){e[0]=a;e[1]=this.pred.get(a);return e},this)}else c=this.pred;return b?X(c,function(a){d=a[0];return D(a[1])},function(a){a[2]=a[1];a[1]=d;return a}):X(c,function(a){d=a[0];return D(a[1])},function(a){a[1]=d;return a})};Z.prototype.in_edges_iter=Z.prototype.T;Z.prototype.Ka=function(a,b){return T(this.T(a,b))};Z.prototype.in_edges=Z.prototype.Ka;
Z.prototype.J=function(a,b){var c;c=a!=l?ub(F(this.j(a),function(a){return[a,this.succ.get(a)]},this),S(this.j(a),function(a){return[a,this.pred.get(a)]},this)):ub(D(this.succ),D(this.pred));return w(b)?S(c,function(a){var c=a[1][1],f=0;a[0][1].forEach(function(a,c){f+=+H(c,b,1)});c.forEach(function(a,c){f+=+H(c,b,1)});return[a[0][0],f]}):F(c,function(a){return[a[0][0],a[0][1].count()+a[1][1].count()]})};Z.prototype.degree_iter=Z.prototype.J;
Z.prototype.ga=function(a,b){var c;c=a!=l?S(this.j(a),function(a){return[a,this.pred.get(a)]},this):this.pred;return b!=l?S(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+H(d,b,1)});a[1]=c;return a}):S(c,function(a){a[1]=a[1].count();return a})};Z.prototype.in_degree_iter=Z.prototype.ga;
Z.prototype.ia=function(a,b){var c;if(a!=l){var d=[];c=S(this.j(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this)}else c=D(this.succ);return b!=l?S(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+H(d,b,1)});return[a[0],c]}):S(c,function(a){return[a[0],a[1].count()]})};Z.prototype.out_degree_iter=Z.prototype.ia;Z.prototype.Ja=function(a,b){return a!=l&&this.l(a)?this.ga(a,b).next()[1]:new O(this.ga(a,b))};Z.prototype.in_degree=Z.prototype.Ja;
Z.prototype.Qa=function(a,b){return a!=l&&this.l(a)?this.ia(a,b).next()[1]:new O(this.ia(a,b))};Z.prototype.out_degree=Z.prototype.Qa;Z.prototype.clear=function(){this.succ.clear();this.pred.clear();this.node.clear();Xa(this.graph)};Z.prototype.clear=Z.prototype.clear;Z.prototype.ha=ba(n);Z.prototype.is_multigraph=Z.prototype.ha;Z.prototype.d=ba(k);Z.prototype.is_directed=Z.prototype.d;Z.prototype.aa=function(){return pb(this)};Z.prototype.to_directed=Z.prototype.aa;
Z.prototype.ba=function(a){var b=new R;b.name(this.name());b.i(this);var c=this.pred,d=[];a?b.f(X(this.q(),function(a){d[0]=a[0];return D(a[1])},function(a){if(c.get(d[0]).a(a[0]))return d[1]=a[0],d[2]=Y(a[1]),d})):b.f(X(this.q(),function(a){d[0]=a[0];return D(a[1])},function(a){d[1]=a[0];d[2]=Y(a[1]);return d}));b.graph=Y(this.graph);b.node=Y(this.node);return b};Z.prototype.to_undirected=Z.prototype.ba;
Z.prototype.reverse=function(a){(a=!s(a)||a)?(a=new this.constructor(l,{name:"Reverse of ("+this.name()+")"}),a.i(this),a.f(S(this.m(l,k),function(a){var c=a[0];a[0]=a[1];a[1]=c;a[2]=Y(a[2]);return a})),a.graph=Y(this.graph),a.node=Y(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Z.prototype.reverse=Z.prototype.reverse;
Z.prototype.$=function(a){a=this.j(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;P(a,function(a){c.set(a,new O);d.set(a,new O)});c.forEach(function(a,b){e.get(a).forEach(function(e,r){c.a(e)&&(b.set(e,r),d.get(e).set(a,r))})});P(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.$;function oc(a,b){var c=U(a),d,e,f=new C;try{e=[c.next()]}catch(g){return g!==B&&h(g),f}f.next=function(){0===e.length&&h(B);return e.splice(0,1)[0]};return X(f,function(a){d=a;return U(b)},function(){try{var a=c.next();e.push(a);return[d,a]}catch(b){b!==B&&h(b)}})}function pc(a,b,c){c=qc(b,c);c.f(oc(b,a));return c}x("jsnx.generators.classic.full_rary_tree",pc);x("jsnx.full_rary_tree",pc);function rc(a,b,c){b=1===a?2:Math.floor((1-Math.pow(a,b+1))/(1-a));c=qc(b,c);c.f(oc(b,a));return c}
x("jsnx.generators.classic.balanced_tree",rc);x("jsnx.balanced_tree",rc);function sc(a,b){var c=qc(a,b);c.name("complete_graph("+a+")");1<a&&c.f(c.d()?xb(U(a)):wb(U(a)));return c}x("jsnx.generators.classic.complete_graph",sc);x("jsnx.complete_graph",sc);function tc(a,b){var c=uc(a,b);c.name("cycle_graph("+a+")");1<a&&c.b(a-1,0);return c}x("jsnx.generators.classic.cycle_graph",tc);x("jsnx.cycle_graph",tc);
function qc(a,b){a instanceof R&&(b=a,a=l);a!=l||(a=0);var c;b!=l?(c=b,c.clear()):c=new R;c.i(U(a));c.name("empty_graph("+a+")");return c}x("jsnx.generators.classic.empty_graph",qc);x("jsnx.empty_graph",qc);
function vc(a,b,c,d){var e=qc(0,d);e.name("grid_2d_graph");d=Qa(U(a));var f=Qa(U(b));A(d,function(a){A(f,function(b){e.I([a,b])})});E(U(1,a),function(a){A(f,function(b){e.b([a,b],[a-1,b])})});A(d,function(a){E(U(1,b),function(b){e.b([a,b],[a,b-1])})});e.d()&&(E(U(0,a-1),function(a){A(f,function(b){e.b([a,b],[a+1,b])})}),A(d,function(a){E(U(0,b-1),function(b){e.b([a,b],[a,b+1])})}));c&&(2<b&&(A(d,function(a){e.b([a,0],[a,b-1])}),e.d()&&A(d,function(a){e.b([a,b-1],[a,0])})),2<a&&(A(f,function(b){e.b([0,
b],[a-1,b])}),e.d()&&A(f,function(b){e.b([a-1,b],[0,b])})),e.name("periodic_grid_2d_graph("+a+","+b+")"));return e}x("jsnx.generators.classic.grid_2d_graph",vc);x("jsnx.grid_2d_graph",vc);function wc(a){a=qc(0,a);a.name("null_graph()");return a}x("jsnx.generators.classic.null_graph",wc);x("jsnx.null_graph",wc);function uc(a,b){var c=qc(a,b);c.name("path_graph("+a+")");c.f(F(U(a-1),function(a){return[a,a+1]}));return c}x("jsnx.generators.classic.path_graph",uc);x("jsnx.path_graph",uc);
function xc(a){a=qc(1,a);a.name("null_graph()");return a}x("jsnx.generators.classic.trivial_graph",xc);x("jsnx.trivial_graph",xc);function yc(a,b,c){c!=l||(c=n);var d=qc(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return zc(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=new Z(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.b(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.b(e,f)}return d}x("jsnx.generators.random_graphs.fast_gnp_random_graph",yc);x("jsnx.fast_gnp_random_graph",yc);
function zc(a,b,c){var d;d=c?new Z:new R;d.i(U(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return sc(a,d);a=d.d()?xb(U(a)):wb(U(a));E(a,function(a){Math.random()<b&&d.b(a[0],a[1])});return d}x("jsnx.generators.random_graphs.gnp_random_graph",zc);x("jsnx.gnp_random_graph",zc);x("jsnx.binomial_graph",zc);x("jsnx.erdos_renyi_graph",zc);function Ac(a,b){Bc(a)||h(new L("Invalid degree sequence"));b!=l&&b.d()&&h(new L("Directed Graph not supported"));var c=a.length,d=qc(c,b);if(0===c||0===Math.max.apply(l,a))return d;for(c=Qa(S(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return n;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return n;for(var f=c.length,g=f-e[0];g<f;g++)d.b(e[1],c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.A()+" nodes "+d.size()+
" edges");return d}x("jsnx.generators.degree_seq.havel_hakimi_graph",Ac);x("jsnx.havel_hakimi_graph",Ac);function Cc(){var a=new R;a.i(U(34));a.name("Zachary's Karate Club");var b=0;A("0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0;1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0;1 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0;1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1;0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1;0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 0 1;0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0".split(";"),
function(c){P(c.split(" "),function(c,e){"1"===c&&a.b(b,e)});b+=1});return a}x("jsnx.generators.social.karate_club_graph",Cc);x("jsnx.karate_club_graph",Cc);
function Dc(){var a=new R;a.i("Evelyn Jefferson;Laura Mandeville;Theresa Anderson;Brenda Rogers;Charlotte McDowd;Frances Anderson;Eleanor Nye;Pearl Oglethorpe;Ruth DeSand;Verne Sanderson;Myra Liddel;Katherina Rogers;Sylvia Avondale;Nora Fayette;Helen Lloyd;Dorothy Murchison;Olivia Carleton;Flora Price".split(";"),{Ea:0});a.i("E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14".split(" "),{Ea:1});a.f([["Evelyn Jefferson","E1"],["Evelyn Jefferson","E2"],["Evelyn Jefferson","E3"],["Evelyn Jefferson","E4"],
["Evelyn Jefferson","E5"],["Evelyn Jefferson","E6"],["Evelyn Jefferson","E8"],["Evelyn Jefferson","E9"],["Laura Mandeville","E1"],["Laura Mandeville","E2"],["Laura Mandeville","E3"],["Laura Mandeville","E5"],["Laura Mandeville","E6"],["Laura Mandeville","E7"],["Laura Mandeville","E8"],["Theresa Anderson","E2"],["Theresa Anderson","E3"],["Theresa Anderson","E4"],["Theresa Anderson","E5"],["Theresa Anderson","E6"],["Theresa Anderson","E7"],["Theresa Anderson","E8"],["Theresa Anderson","E9"],["Brenda Rogers",
"E1"],["Brenda Rogers","E3"],["Brenda Rogers","E4"],["Brenda Rogers","E5"],["Brenda Rogers","E6"],["Brenda Rogers","E7"],["Brenda Rogers","E8"],["Charlotte McDowd","E3"],["Charlotte McDowd","E4"],["Charlotte McDowd","E5"],["Charlotte McDowd","E7"],["Frances Anderson","E3"],["Frances Anderson","E5"],["Frances Anderson","E6"],["Frances Anderson","E8"],["Eleanor Nye","E5"],["Eleanor Nye","E6"],["Eleanor Nye","E7"],["Eleanor Nye","E8"],["Pearl Oglethorpe","E6"],["Pearl Oglethorpe","E8"],["Pearl Oglethorpe",
"E9"],["Ruth DeSand","E5"],["Ruth DeSand","E7"],["Ruth DeSand","E8"],["Ruth DeSand","E9"],["Verne Sanderson","E7"],["Verne Sanderson","E8"],["Verne Sanderson","E9"],["Verne Sanderson","E12"],["Myra Liddel","E8"],["Myra Liddel","E9"],["Myra Liddel","E10"],["Myra Liddel","E12"],["Katherina Rogers","E8"],["Katherina Rogers","E9"],["Katherina Rogers","E10"],["Katherina Rogers","E12"],["Katherina Rogers","E13"],["Katherina Rogers","E14"],["Sylvia Avondale","E7"],["Sylvia Avondale","E8"],["Sylvia Avondale",
"E9"],["Sylvia Avondale","E10"],["Sylvia Avondale","E12"],["Sylvia Avondale","E13"],["Sylvia Avondale","E14"],["Nora Fayette","E6"],["Nora Fayette","E7"],["Nora Fayette","E9"],["Nora Fayette","E10"],["Nora Fayette","E11"],["Nora Fayette","E12"],["Nora Fayette","E13"],["Nora Fayette","E14"],["Helen Lloyd","E7"],["Helen Lloyd","E8"],["Helen Lloyd","E10"],["Helen Lloyd","E11"],["Helen Lloyd","E12"],["Dorothy Murchison","E8"],["Dorothy Murchison","E9"],["Olivia Carleton","E9"],["Olivia Carleton","E11"],
["Flora Price","E9"],["Flora Price","E11"]]);return a}x("jsnx.generators.social.davis_southern_women_graph",Dc);x("jsnx.davis_southern_women_graph",Dc);
function Ec(){var a=new R;a.b("Acciaiuoli","Medici");a.b("Castellani","Peruzzi");a.b("Castellani","Strozzi");a.b("Castellani","Barbadori");a.b("Medici","Barbadori");a.b("Medici","Ridolfi");a.b("Medici","Tornabuoni");a.b("Medici","Albizzi");a.b("Medici","Salviati");a.b("Salviati","Pazzi");a.b("Peruzzi","Strozzi");a.b("Peruzzi","Bischeri");a.b("Strozzi","Ridolfi");a.b("Strozzi","Bischeri");a.b("Ridolfi","Tornabuoni");a.b("Tornabuoni","Guadagni");a.b("Albizzi","Ginori");a.b("Albizzi","Guadagni");a.b("Bischeri",
"Guadagni");a.b("Guadagni","Lamberteschi");return a}x("jsnx.generators.social.florentine_families_graph",Ec);x("jsnx.florentine_families_graph",Ec);function Fc(a,b){b!=l&&b.d()&&h(new L("Directed Graph not supported"));return Gc(a,b)}x("jsnx.generators.small.make_small_undirected_graph",Fc);function Gc(a,b){var c=a[0],d=a[1],e=a[2],f=qc(e,b),g=f.nodes();if("adjacencylist"==c){var m=a[3];m.length!=e&&h(new L("invalid graph_description"));A(g,function(a){P(m[a],function(b){f.b(b-1,a)})})}else"edgelist"==c&&P(a[3],function(a){var b=a[0]-1;a=a[1]-1;(0>b||b>e-1||0>a||a>e-1)&&h(new L("invalid graph_description"));f.b(b,a)});f.name=d;return f}
x("jsnx.generators.small.make_small_graph",Gc);x("jsnx.make_small_graph",Gc);function Hc(a){return Fc(["adjacencylist","Bull Graph",5,[[2,3],[1,3,4],[1,2,5],[2],[3]]],a)}x("jsnx.generators.small.bull_graph",Hc);x("jsnx.bull_graph",Hc);function Ic(a){return Fc(["adjacencylist","Krackhardt Kite Social Network",10,[[2,3,4,6],[1,4,5,7],[1,4,6],[1,2,3,5,6,7],[2,4,7],[1,3,4,7,8],[2,4,5,6,8],[6,7,9],[8,10],[9]]],a)}x("jsnx.generators.small.krackhardt_kite_graph",Ic);x("jsnx.krackhardt_kite_graph",Ic);function Jc(a,b){a.d()&&h(new L("triangles() is not defined for directed graphs."));if(b!=l&&a.l(b))return Math.floor(Kc(a,b).next()[2]/2);var c=new O;E(Kc(a,b),function(a){c.set(a[0],Math.floor(a[2]/2))});return c}x("jsnx.algorithms.cluster.triangles",Jc);x("jsnx.triangles",Jc);
function Kc(a,b){var c;c=b!=l?X(a.j(b),function(b){return[b,a.get(b)]}):D(a.adj);return F(c,function(b){var c=new Q(b[1].keys()),f=0;c.remove(b[0]);E(c,function(b){var d=new Q(a.get(b).keys());d.remove(b);f+=c.o(d).count()});return[b[0],c.count(),f]})}
function Lc(a,b,c){w(c)||(c="weight");var d;d=0===a.ra()?1:vb(a.K(k),function(a){return H(a[2],c,1)});b=b!=l?X(a.j(b),function(b){return[b,a.get(b)]}):D(a.adj);return F(b,function(b){var f=b[0],g=new Q(b[1].keys());g.remove(f);var m=0,r=new Q;E(g,function(b){var e=H(a.get(f).get(b),c,1)/d;r.add(b);var y=(new Q(a.get(b).keys())).C(r);E(g.o(y),function(g){var r=H(a.get(b).get(g),c,1)/d;g=H(a.get(f).get(g),c,1)/d;m+=Math.pow(e*r*g,1/3)})});return[f,g.count(),2*m]})}
function Mc(a,b,c,d){2===arguments.length?w(b)?(c=b,b=l):fa(b)&&(d=b,b=l):3===arguments.length&&fa(c)&&(d=c,c=l);d!=l||(d=k);var e=Nc(a,b,c).n();d||(e=sa(e,function(a){return 0<a}));return K.B.apply(K,e)/e.length}x("jsnx.algorithms.cluster.average_clustering",Mc);x("jsnx.average_clustering",Mc);
function Nc(a,b,c){a.d()&&h(new L("Clustering algorithms are not defined for directed graphs."));c=c!=l?Lc(a,b,c):Kc(a,b);var d=new O;E(c,function(a){d.set(a[0],0===a[2]?0:a[2]/(a[1]*(a[1]-1)))});return b!=l&&a.l(b)?d.n()[0]:d}x("jsnx.algorithms.cluster.clustering",Nc);x("jsnx.clustering",Nc);function Oc(a){var b=0,c=0;E(Kc(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c}x("jsnx.algorithms.cluster.transitivity",Oc);x("jsnx.transitivity",Oc);
function Pc(a,b){var c=b==l?tb(a):a.j(b),d=new O;E(c,function(b){d.set(b,0);var c=0;E(wb(a.get(b).keys()),function(g){var m=g[0];g=g[1];var r=(new Q(a.get(m).keys())).o(a.get(g).keys());r.remove(b);r=r.count();d.set(b,d.get(b)+r);var u=r+1;a.get(m).a(g)&&(u+=1);c+=(a.get(m).count()-u)*(a.get(g).count()-u)+r});0<c&&d.set(b,d.get(b)/c)});return b!=l&&a.l(b)?d.n()[0]:d}x("jsnx.algorithms.cluster.square_clustering",Pc);x("jsnx.square_clustering",Pc);function Qc(a){var b=-1,c=new O,d=new Q;E(a.q(),function(a){var e=new Q(a[1].keys());e.remove(a[0]);var f=e.count();f>b?(c.set(a[0],e),d=e,b=f):c.set(a[0],e)});var e=new Q(c.keys()),f=e.C(d),g=new Q,m=[],r=[];a=new C;a.next=function(){0===f.count()&&0===m.length&&h(B);var a,v;if(0<f.count())a=D(f).next(),f.remove(a);else{var y=m.pop();e=y[0];g=y[1];f=y[2];r.pop();return this.next()}r.push(a);e.remove(a);g.add(a);var I=c.get(a),y=e.o(I),I=g.o(I);if(0===y.count()&&(0===I.count()&&(v=Ca(r)),r.pop(),
v))return v;if(0===I.count()&&1===y.count())return v=ya(r,y.n()),r.pop(),v;var Ha=y.count(),V=-1,W,M;for(v=D(I);(a=Ra(v,l))!==l&&!(a=y.o(c.get(a)),M=a.count(),M>V&&(W=a,V=M,V===Ha)););if(V===Ha)return r.pop(),this.next();b=-1;for(v=D(y);(a=Ra(v,l))!==l&&!(a=y.o(c.get(a)),M=a.count(),M>b&&(d=a,b=M,b===Ha-1)););V>b&&(d=W);m.push([e,g,f]);e=y;g=I;f=e.C(d);return this.next()};return a}x("jsnx.algorithms.clique.find_cliques",Qc);x("jsnx.find_cliques",Qc);
function Rc(a){var b=new O;E(a.q(),function(a){var c=new Q(a[1].keys());c.remove(a[0]);b.set(a[0],c)});if(0===b.count())return[];a=new Q(b.keys());var c=new Q,d=[];Sc(b,a,c,[],d);return d}x("jsnx.algorithms.clique.find_cliques_recursive",Rc);x("jsnx.find_cliques_recursive",Rc);
function Sc(a,b,c,d,e){var f=-1,g=b.count(),m,r,u,v;for(r=D(c);(u=Ra(r,l))!==l;)if(u=b.o(a.get(u)),v=u.count(),v>f&&(m=u,f=v,v===g))return;E(b,function(c){c=b.o(a.get(c));var d=c.count();d>f&&(m=c,f=d)});g=b.C(m);E(g,function(f){b.remove(f);d.push(f);var g=a.get(f);f=b.o(g);g=c.o(g);0===f.count()&&0===g.count()?e.push(Ca(d)):0===g.count()&&1===f.count()?e.push(ya(d,f.n())):Sc(a,f,g,d,e);c.add(d.pop())})}function Tc(a,b){b!=l||(b=Qc(a));var c=0;P(b,function(a){c=a.length>c?a.length:c});return c}
x("jsnx.algorithms.clique.graph_clique_number",Tc);x("jsnx.graph_clique_number",Tc);function Uc(a,b){b!=l||(b=Qc(a));return T(b).length}x("jsnx.algorithms.clique.graph_number_of_cliques",Uc);x("jsnx.graph_number_of_cliques",Uc);function Vc(a,b,c){c=c!=l?Qa(c):Qa(Qc(a));b!=l||(b=a.nodes());var d;if(ea(b))d=new O,A(b,function(a){d.set(a,sa(c,function(b){return(new Q(b)).a(a)}).length)});else{var e=b;d=sa(c,function(a){return(new Q(a)).a(e)}).length}return d}
x("jsnx.algorithms.clique.number_of_cliques",Vc);x("jsnx.number_of_cliques",Vc);function Wc(a,b){if(a.A()!=b.A())return n;var c=a.z(),d=Jc(a),e=Vc(a),f=[];c.forEach(function(a){f.push([c.get(a),d.get(a),e.get(a)])});f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var g=b.z(),m=Jc(b),r=Vc(b),u=[];g.forEach(function(a){u.push([g.get(a),m.get(a),r.get(a)])});u.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!Fa(f,u,function(a,b){return Fa(a,b)})?n:k}x("jsnx.algorithms.isomorphism.could_be_isomorphic",Wc);
x("jsnx.could_be_isomorphic",Wc);function Xc(a,b){if(a.A()!=b.A())return n;var c=a.z(),d=Jc(a),e=[];c.forEach(function(a){e.push([c.get(a),d.get(a)])});e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var f=b.z(),g=Jc(b),m=[];f.forEach(function(a){m.push([f.get(a),g.get(a)])});m.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!Fa(e,m,function(a,b){return Fa(a,b)})?n:k}x("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Xc);x("jsnx.fast_could_be_isomorphic",Xc);
function Yc(a,b){if(a.A()!=b.A())return n;var c=a.z().n();c.sort();var d=b.z().n();d.sort();return!Fa(c,d)?n:k}x("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Yc);x("jsnx.faster_could_be_isomorphic",Yc);function Zc(){}Zc.oa=function(){return Zc.pa?Zc.pa:Zc.pa=new Zc};Zc.prototype.Ma=0;Zc.oa();function $c(a){if(!t(a))return n;for(var b=0,c=a.length;b<c;b++)if(isNaN(a[b]))return n;return k}x("jsnx.utils.misc.is_list_of_ints",$c);x("jsnx.utils.is_list_of_ints",$c);function ad(a){var b=0;return F(a,function(a){return b+=a})}x("jsnx.utils.misc.cumulative_sum",ad);x("jsnx.utils.cumulative_sum",ad);function bd(){return":"+(Zc.oa().Ma++).toString(36)}x("jsnx.utils.misc.generate_unique_node",bd);x("jsnx.utils.generate_unique_node",bd);function Bc(a,b){if("eg"===b)return cd(a);if(b==l||"hh"===b)return dd(a);h(new db("`opt_method` must be 'eg' or 'hh'"))}x("jsnx.algorithms.graphical.is_valid_degree_sequence",Bc);x("jsnx.is_valid_degree_sequence",Bc);function dd(a){if(0===a.length)return k;if(!$c(a)||0>Math.min.apply(l,a)||0!==K.B.apply(l,a)%2)return n;for(a=Ca(a);0<a.length;){z.sort.call(a,La);if(0>a[0])break;var b=a.pop();if(0===b)return k;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return n}
x("jsnx.algorithms.graphical.is_valid_degree_sequence_havel_hakimi",dd);x("jsnx.is_valid_degree_sequence_havel_hakimi",dd);
function cd(a){if(0===a.length)return k;if(!$c(a)||0>Math.min.apply(l,a)||0!==K.B.apply(l,a)%2)return n;var b=a.length,c=Ca(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=K.B.apply(l,c.slice(0,d[e])),g=d[e]*(d[e]-1)+K.B.apply(l,Qa(F(U(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return n;return k}x("jsnx.algorithms.graphical.is_valid_degree_sequence_erdos_gallai",cd);
x("jsnx.is_valid_degree_sequence_erdos_gallai",cd);function ed(a){try{return fd(a),k}catch(b){if(b instanceof jb)return n;h(b)}}x("jsnx.algorithms.dag.is_directed_acyclic_graph",ed);x("jsnx.is_directed_acyclic_graph",ed);
function fd(a,b){a.d()||h(new L("Topological sort not defined on undirected graphs."));var c=new Q,d=[],e=new Q;b!=l||(b=a.H());P(b,function(b){if(!e.a(b))for(b=[b];0<b.length;){var g=b[b.length-1];if(e.a(g))b.pop();else{c.add(g);var m=[];a.get(g).forEach(function(a){e.a(a)||(c.a(a)&&h(new jb("Graph contains a cycle")),m.push(a))});0<m.length?b.push.apply(b,m):(e.add(g),Da(d,aa,0,g))}}});return d}x("jsnx.algorithms.dag.topological_sort",fd);x("jsnx.topological_sort",fd);
function gd(a,b){function c(a,b,d,e){b.add(e);a.get(e).forEach(function(e){if(b.a(e))b.a(e)&&!(0<=ra(d,e))&&h(new jb("Graph contains a cycle"));else if(!c(a,b,d,e))return n});Da(d,aa,0,e);return k}a.d()||h(new L("Topological sort not defined on undirected graphs."));var d=new Q,e=[];b!=l||(b=a.H());P(b,function(b){!(0<=ra(e,b))&&!c(a,d,e,b)&&h(new jb("Graph contains a cycle"))});return e}x("jsnx.algorithms.dag.topological_sort_recursive",gd);x("jsnx.topological_sort_recursive",gd);
var id=function hd(b){b.d()||h(new L("is_aperiodic not defined for undirected graphs."));var c=b.H().next(),d=new O;d.set(c,0);for(var c=[c],e=0,f=1;0<c.length;){var g=[];A(c,function(c){b.get(c).forEach(function(b){d.a(b)?e=Bb(e,d.get(c)-d.get(b)+1):(g.push(b),d.set(b,f))})});c=g;f+=1}return d.count()===rb(b)?1===e:1===e&&hd(b.$((new Q(b.nodes())).C(d.keys())))};x("jsnx.algorithms.dag.is_aperiodic",id);x("jsnx.is_aperiodic",id);function jd(a,b){this.qa=a;this.la=b}jd.prototype.getKey=function(){return this.qa};jd.prototype.R=function(){return new jd(this.qa,this.la)};function kd(a){this.p=[];if(a)a:{var b,c;if(a instanceof kd){if(b=a.da(),c=a.D(),0>=a.S()){a=this.p;for(var d=0;d<b.length;d++)a.push(new jd(b[d],c[d]));break a}}else b=Wa(a),c=Va(a);for(d=0;d<b.length;d++)ld(this,b[d],c[d])}}function ld(a,b,c){var d=a.p;d.push(new jd(b,c));b=d.length-1;a=a.p;for(c=a[b];0<b;)if(d=b-1>>1,a[d].getKey()>c.getKey())a[b]=a[d],b=d;else break;a[b]=c}p=kd.prototype;
p.remove=function(){var a=this.p,b=a.length,c=a[0];if(!(0>=b)){if(1==b)wa(a);else{a[0]=a.pop();for(var a=0,b=this.p,d=b.length,e=b[a];a<d>>1;){var f=2*a+1,g=2*a+2,f=g<d&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>e.getKey())break;b[a]=b[f];a=f}b[a]=e}return c.la}};p.D=function(){for(var a=this.p,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].la);return b};p.da=function(){for(var a=this.p,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};
p.na=function(a){return va(this.p,function(b){return b.getKey()==a})};p.R=function(){return new kd(this)};p.S=function(){return this.p.length};p.U=function(){return 0==this.p.length};p.clear=function(){wa(this.p)};function md(){kd.call(this)}na(md,kd);function nd(a,b){ld(a,0,b)};function od(a,b){b!=l||(b={});"object"!==q(b)&&h(new L("The arg_dict argument must be an object."));var c=qb(a),d=a.nodes();"k"in b&&(Na(d),d=d.slice(0,b.k));P(d.sort(),function(d){var f=[],f=H(b,"weight",l)===l?pd(a,d):qd(a,d,b.weight),g=f[0],m=f[1],f=f[2];c=H(b,"endpoints",n)?rd(c,g,m,f,d):ud(c,g,m,f,d)});return c=vd(c,rb(a),H(b,"normalized",k),a.d(),H(b,"k",l))}x("jsnx.algorithms.centrality.betweenness.betweenness_centrality",od);x("jsnx.betweenness_centrality",od);
function wd(a,b){b!=l||(b={});"object"!==q(b)&&h(new L("The arg_dict argument must be an object."));var c=qb(a);E(a.m(),function(a){c.set(a,0)});var d=a.nodes();P(d.sort(),function(d){var f=[],f=H(b,"weight",l)===l?pd(a,d):qd(a,d,b.weight);c=xd(c,f[0],f[1],f[2],d)});P(d,function(a){c.remove(a)});return c=yd(c,rb(a),H(b,"normalized",k),a.d())}x("jsnx.algorithms.centrality.betweenness.edge_betweenness_centrality",wd);x("jsnx.edge_betweenness_centrality",wd);
function pd(a,b){var c=[],d=new O;E(a.H(),function(a){d.set(a,[])});var e=qb(a),f=new O;e.set(b,1);f.set(b,0);for(var g=[b];0<g.length;){var m=g.shift();c.push(m);var r=f.get(m),u=e.get(m);A(a.F(m),function(a){f.a(a)||(g.push(a),f.set(a,r+1));f.get(a)===r+1&&(e.set(a,e.get(a)+u),d.get(a).push(m))})}return[c,d,e]}
function qd(a,b,c){var d=[],e=new O;P(a.nodes(),function(a){e.set(a,[])});var f=qb(a),g=new O;f.set(b,1);var m=new O;m.set(b,0);var r=new md;for(nd(r,[b,b]);!r.U();){var u=r.p[0]&&r.p[0].getKey();b=r.remove();var v=b[0],y=b[1];g.a(y)||(f.set(y,f.get(y)+f.get(v)),d.push(y),g.set(y,u),E(a.m(y,k),function(a){var b=a[1];a=u+H(a[2],c,1);!g.a(b)&&(!m.a(b)||a<m.get(b))?(m.set(b,a),ld(r,a,[y,b]),f.set(b,0),e.set(b,[y])):a===m.get(b)&&(f.set(b,f.get(b)+f.get(y)),e.get(b).push(y))}))}return[d,e,f]}
function ud(a,b,c,d,e){for(var f=qb(b);0<b.length;){var g=b.pop(),m=(1+f.get(g))/d.get(g);A(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*m)});(g!==e||ha(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function rd(a,b,c,d,e){a.set(e,a.get(e)+b.length-1);for(var f=qb(b);0<b.length;){var g=b.pop(),m=(1+f.get(g))/d.get(g);A(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*m)});(g!==e||ha(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g)+1)}return a}
function xd(a,b,c,d,e){for(var f=qb(b);0<b.length;){var g=b.pop(),m=(1+f.get(g))/d.get(g);A(c.get(g),function(b){var c=d.get(b)*m,e=[b,g];a.a(e)||(e=[g,b]);a.set(e,a.get(e)+c);f.set(b,f.get(b)+c)});(g!==e||ha(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function vd(a,b,c,d,e){var f;fa(c)&&c?2<b&&(f=1/((b-1)*(b-2))):fa(d)&&!d&&(f=0.5);s(f)&&(e!=l&&(f=f*b/e),a.forEach(function(b,c){a.set(b,c*f)}));return a}
function yd(a,b,c,d){var e;fa(c)&&c?1<b&&(e=1/(b*(b-1))):fa(d)&&!d&&(e=0.5);s(e)&&a.forEach(function(b,c){a.set(b,c*e)});return a};function zd(a,b,c){var d=new O,e=0,f=new O;for(f.set(b,1);0<f.count();){b=f;f=new O;b.forEach(function(b){d.a(b)||(d.set(b,e),a.get(b).forEach(function(a){f.set(a,1)}))});if("number"==typeof c&&c<=e)break;e+=1}return d}x("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path_length",zd);x("jsnx.single_source_shortest_path_length",zd);function Ad(a,b){var c=new O;P(a,function(d){c.set(d,zd(a,d,b))});return c}
x("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length",Ad);x("jsnx.all_pairs_shortest_path_length",Ad);function Bd(a,b,c){c=Cd(a,b,c);a=c[0];b=c[1];c=c[2];for(var d=[];c!=l;)d.push(c),c=b.get(c);for(c=a.get(d[0]);c!=l;)d.unshift(c),c=a.get(c);return d}x("jsnx.algorithms.shortest_paths.unweighted.bidirectional_shortest_path",Bd);x("jsnx.bidirectional_shortest_path",Bd);
function Cd(a,b,c){(!s(b)||!s(c))&&h(new db("Bidirectional shortest path called without source or target"));var d=new O,e=new O;if(c===b)return d.set(c,l),e.set(b,l),[d,e,b];var f,g;a.d()?(f=a.ta,g=a.ka):g=f=a.O;d.set(b,l);e.set(c,l);for(var m=[b],r=[c],u,v;0<m.length&&0<r.length&&!v;)m.length<=r.length?(u=m,m=[],A(u,function(b){v||E(g.call(a,b),function(a){v||(d.a(a)||(m.push(a),d.set(a,b)),e.a(a)&&(v=[d,e,a]))})})):(u=r,r=[],A(u,function(b){v||E(f.call(a,b),function(a){v||(e.a(a)||(e.set(a,b),r.push(a)),
d.a(a)&&(v=[d,e,a]))})}));if(v)return v;h(new kb("No path between "+b+" and "+c+"."))}function Dd(a,b,c){var d=0,e=new O([[b,1]]),f=new O([[b,[b]]]);if(0===c)return f;for(;0<e.count()&&!(b=e,e=new O,b.forEach(function(b){a.get(b).forEach(function(a){f.a(a)||(f.set(a,f.get(b).concat([a])),e.set(a,1))})}),d+=1,s(c)&&c<=d););return f}x("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path",Dd);x("jsnx.single_source_shortest_path",Dd);
function Ed(a,b){var c=new O;P(a,function(d){c.set(d,Dd(a,d,b))});return c}x("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path",Ed);x("jsnx.all_pairs_shortest_path",Ed);
function Fd(a,b,c,d,e){for(var f=0,g=[b],m=new O([[b,f]]),r=new O([[b,[]]]);0<g.length&&!(f+=1,b=g,g=[],A(b,function(b){a.get(b).forEach(function(a){m.a(a)?m.get(a)===f&&r.get(a).push(b):(r.set(a,[b]),m.set(a,f),g.push(a))})}),d!=l&&d<=f););return c!=l?e?!r.a(c)?[[],-1]:[r.get(c),m.get(c)]:!r.a(c)?[]:r.get(c):e?[r,m]:r}x("jsnx.algorithms.shortest_paths.unweighted.predecessor",Fd);x("jsnx.predecessor",Fd);}));
